### ISSUE TITLE
long_running.cpp: Boost Asio Equivalent

### ISSUE THREAD

**Issue by WarrenN1** [madmongo1/asio_experiments#3]
Hello,
I was wondering if there is a boost asio based equivalent to the semaphore solution you created here?  I am currently trying to develop a webserver with a main io_ctx using 5 threads and a worker threadpool of N threads for handling blocking work. The goal would be for the main io_ctx which runs the webserver to within the coroutine send work to the worker threadpool and await for it to finish and then continue along in the main io_ctx to finish the work. That way the blocking work doesn't slow down the main io loop. I have been trying to go through the boost docs, but I have been struggling with finding what I am looking for and was hoping you could point me in the right direction or provide some assistance.

Thank you again for everything you have done for the open source community. I just graduated University recently and wanted to give my idea a try before going to get a traditional job. This project I am working on would not be possible without you and the other developers who maintain boost and other libraries.

**Comment by madmongo1** [comment]
Sending work to the thread pool:

```
// given:
// ioex = strand of executor of io_service
// wex = executor or thread pool

// assume we are on the io executor at this point:
asio::ip::tcp::socket& stream;
beast::flat_buffer& rxbuf;

auto req = http::request();
auto rxsize = co_await http::async_read(stream, rxbuf, req, asio::use_awaitable);

auto resp = http::response();
// this is a suspension point - other IO work will continue while perform_work is running on the thread pool
co_spawn(asio::make_strand(wex), 
                 perform_work(req, resp),
                 asio::use_awaitable);
// perform_work is now complete, our response has been filled in
co_await http::async_write(stream, resp, asio::use_awaitable);

// query processed
```

Note that in general, using more than one IO thread is unnecessary, and is often counterproductive unless you have specialised hardware. The network card is a mutex, and sending data over the write is likely to take longer than the CPU takes to co-ordinate sending and receiving it.

**Comment by WarrenN1** [comment]
Thank you so much for your response and time!
In your note, you mentioned that using more than one IO thread is unnecessary. How would you suggest handling blocking work on the io_ctx then? I am definitely open to suggestions. My design as of now is: 
1) My main io_ctx has N threads for the network heavy workload
2) My threadpool has M threads where M >> N for blocking synchronous work (using ancient DB API's for example).

I use the standard co_ssl boost server (slightly modified for URI parsing etc). Then in the handle_request call I am planning on doing what you illustrated above calling co_spawn on the threadpool seperate from the threads I dedicated to my IO.

By more than 1 IO thread being unnecessary, do you mean that my design should be:
1) My main io_ctx has N=1 thread for the network workload.
2) My threadpool has M threads where M >> N for blocking synchronous work (using ancient DB API's for example).

**Comment by klemens-morgenstern** [comment]
yes you offload the work from the io_ctx onto the threadpool.

Richard's examples with `co_spawn` will executor the awaitable on the `wex` and then dispatch the result back to the original executor. So you await it from the io_ctx. You don't even need the strand if it's just one awaitable.

so basically;

```cpp
asio::awaitable<string> heavy_work(std::string data); //will run on the thread_pool

// co_spawn this on the io_ctx
asio::awaitable<void> single_io_op(asio::ip::tcp::socket & sock, asio::thread_pool & tp)
{
    //pseudo code for simplicity sake
    auto data = co_await sock.async_read();

    // this will block this coro, but io_ctx can do other work on other connections
   auto res =  co_await co_spawn(tp, heavy_work(data), asio::use_awaitable);
   co_await sock.async_write(res);
}


```

**Comment by WarrenN1** [comment]
The problem is that I am compiling with C++ 14 as I need access to some URL parsers etc. and other libraries so I do not have access to co_await which is only for C++20.

**Comment by WarrenN1** [comment]
Solved the problem with coroutines and upgraded other libraries.
